"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

import pymysql
pymysql.install_as_MySQLdb()
import MySQLdb
MySQLdb.version_info = (2, 2, 6, "final", 0)
from pathlib import Path


def _cargar_archivo_entorno(ruta_archivo):
    """Carga variables clave=valor desde un archivo .env local."""
    if not ruta_archivo.exists():
        return

    for linea in ruta_archivo.read_text(encoding='utf-8').splitlines():
        linea_limpia = linea.strip()
        if not linea_limpia or linea_limpia.startswith('#'):
            continue
        if '=' not in linea_limpia:
            continue

        clave, valor = linea_limpia.split('=', 1)
        clave = clave.strip()
        valor = valor.strip().strip('"').strip("'")
        if clave:
            os.environ.setdefault(clave, valor)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
_cargar_archivo_entorno(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ndrl1!l22)rjr5+)4iv9n2ycu#)$q8+up1u+xkk#z-)0t@4=s!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'http://cytechn.ddns.net', 'cytechn.ddns.net', '192.168.1.69']

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Librerías de terceros
    'rest_framework',
    'simple_history',
    'django_celery_beat',
    # Apps del proyecto
    'core',
    'configuraciones_globales',
    'sucursales',
    'fondos_fijos',
    'usuarios',
    'categoria_operativa',
    'reportes_diarios',
    'estado_resultados',
    'libro_estado_resultados',
    'configuraciones_usuario',
    'cabina_arquitectura',
]

AUTH_USER_MODEL = 'usuarios.Usuario'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# base de datos para despliegue en servidor remoto
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'apex_ton',
        'USER': 'robert',
        'PASSWORD': 'Chido1993$',
        'HOST': 'cytechn.ddns.net', #ip servidor en red local 192.168.1.69
        'PORT': '3306',
    }
}
# base de datos para local 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'apex_ton',
#         'USER': 'root',
#         'PASSWORD': 'root',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Prefijo de subcarpeta para despliegue conjunto con frontend. Si se va a desplegar en la raíz, dejar vacío ''.
SUBCARPETA_BASE_APEX = '/apex'
FORCE_SCRIPT_NAME = SUBCARPETA_BASE_APEX

STATIC_URL = f'{SUBCARPETA_BASE_APEX}/static/'
MEDIA_URL = f'{SUBCARPETA_BASE_APEX}/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Celery ──────────────────────────────────────────────────────────────────
# Broker por defecto en servidor: RabbitMQ.
# Formato recomendado: amqp://usuario:password@host:5672/vhost
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'amqp://guest:guest@127.0.0.1:5672//')
# RabbitMQ no requiere backend de resultados para este flujo, por eso se usa rpc://.
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'rpc://')
CELERY_TIMEZONE           = 'America/Mexico_City'
CELERY_ENABLE_UTC         = False
CELERY_ACCEPT_CONTENT     = ['json']
CELERY_TASK_SERIALIZER    = 'json'
CELERY_RESULT_SERIALIZER  = 'json'
CELERY_BEAT_SCHEDULER     = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# ── django-simple-history ───────────────────────────────────────────────────
HISTORY_USER_MODEL = AUTH_USER_MODEL


def _obtener_booleano_entorno(nombre_variable, valor_predeterminado):
    """Convierte valores de entorno en booleanos de forma tolerante."""
    valor = os.getenv(nombre_variable)
    if valor is None:
        return valor_predeterminado
    return valor.strip().lower() in {'1', 'true', 't', 'si', 's', 'yes', 'y', 'on'}


# ── Correo saliente (SMTP) ──────────────────────────────────────────────────
# Configuracion preparada para robertot@gbentretenimiento.com.
# Valor por defecto orientado a Google Workspace / Gmail SMTP.
# Usar DJANGO_EMAIL_HOST_PASSWORD con contrasena de aplicacion.
EMAIL_BACKEND = os.getenv('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', '587'))
EMAIL_USE_TLS = _obtener_booleano_entorno('DJANGO_EMAIL_USE_TLS', True)
EMAIL_USE_SSL = _obtener_booleano_entorno('DJANGO_EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', 'robertot@gbentretenimiento.com')
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = int(os.getenv('DJANGO_EMAIL_TIMEOUT', '20'))
DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SERVER_EMAIL = os.getenv('DJANGO_SERVER_EMAIL', EMAIL_HOST_USER)

# ── Enlaces públicos para notificaciones de credenciales ───────────────────
# Dashboard principal del sistema para usuarios finales.
URL_PUBLICA_DASHBOARD_BINSUR = os.getenv('URL_PUBLICA_DASHBOARD_BINSUR', 'https://cytechn.ddns.net/apex/')
# Ruta de login usada en correos de bienvenida y reinicio de contraseña.
URL_PUBLICA_LOGIN_BINSUR = os.getenv('URL_PUBLICA_LOGIN_BINSUR', 'https://cytechn.ddns.net/apex/auth/login')
