# Generated by Django 6.0.2 on 2026-03-20 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('sistema', 'Seguir sistema operativo')], default='sistema', help_text="Preferencia de tema visual: 'claro', 'oscuro' o 'sistema' (sigue la preferencia del SO del usuario).", max_length=20, verbose_name='Tema de color')),
                ('color_acento', models.CharField(choices=[('azul', 'Azul'), ('morado', 'Morado'), ('verde', 'Verde'), ('naranja', 'Naranja'), ('rojo', 'Rojo'), ('cyan', 'Cyan'), ('personalizado', 'Personalizado (usa color_hex)')], default='azul', help_text='Color principal de la interfaz seleccionado por el usuario.', max_length=20, verbose_name='Color de acento')),
                ('color_hex', models.CharField(blank=True, help_text="Color en formato hexadecimal (#RRGGBB) cuando color_acento='personalizado'. Ejemplo: '#7C3AED'.", max_length=7, null=True, verbose_name='Color HEX personalizado')),
                ('densidad_ui', models.CharField(choices=[('compacta', 'Compacta'), ('normal', 'Normal'), ('espaciosa', 'Espaciosa')], default='normal', help_text="Controla el espaciado general de la UI: 'compacta' para más filas visibles, 'espaciosa' para mejor legibilidad.", max_length=20, verbose_name='Densidad de la interfaz')),
                ('tamano_fuente', models.PositiveSmallIntegerField(default=14, help_text='Tamaño base de la tipografía en píxeles. Rango recomendado: 12–20px.', verbose_name='Tamaño de fuente (px)')),
                ('formato_fecha', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', help_text='Formato preferido para mostrar fechas en la interfaz.', max_length=12, verbose_name='Formato de fecha')),
                ('separador_miles', models.CharField(choices=[(',', 'Coma (1,000.00)'), ('.', 'Punto (1.000,00)')], default=',', help_text='Carácter utilizado como separador de miles en cifras monetarias.', max_length=1, verbose_name='Separador de miles')),
                ('menu_colapsado', models.BooleanField(default=False, help_text='Si es True, el menú lateral de navegación inicia siempre colapsado.', verbose_name='Menú lateral colapsado')),
                ('pagina_inicio', models.CharField(default='dashboard', help_text="Ruta o nombre de la vista que se carga al iniciar sesión (ej. 'dashboard', 'reportes').", max_length=100, verbose_name='Página de inicio')),
                ('filas_por_pagina', models.PositiveSmallIntegerField(default=25, help_text='Número de registros mostrados por defecto en las paginaciones de tablas de datos. Valores comunes: 10, 25, 50, 100.', verbose_name='Filas por página en tablas')),
                ('notificaciones_activas', models.BooleanField(default=True, help_text='Habilita o deshabilita las notificaciones en tiempo real dentro de la aplicación.', verbose_name='Notificaciones activas')),
                ('sonido_notificaciones', models.BooleanField(default=False, help_text='Si es True, se reproduce un sonido al recibir notificaciones en la app.', verbose_name='Sonido en notificaciones')),
                ('preferencias_extra', models.JSONField(blank=True, default=dict, help_text='Campo JSON de extensión genérica para almacenar preferencias futuras sin necesidad de migración. Ejemplo: {"mostrar_tips": true, "columnas_ocultas": ["rfc", "correo"]}.', verbose_name='Preferencias adicionales')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('usuario', models.OneToOneField(help_text='Usuario propietario de estas preferencias de configuración. Relación 1:1.', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuarios',
                'db_table': 'configuraciones_usuario',
            },
        ),
    ]
