# Generated by Django 6.0.2 on 2026-03-20 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0003_alter_sucursal_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroEstadoResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('anio', models.PositiveSmallIntegerField(help_text='Año contable del período (ej. 2026).', verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(help_text='Mes contable del período (1=Enero … 12=Diciembre).', verbose_name='Mes')),
                ('estado_mes', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', help_text='ABIERTO: mes en curso. CERRADO: mes cerrado e inmutable.', max_length=10, verbose_name='Estado del Mes')),
                ('tipo_cambio_usd_snapshot', models.DecimalField(decimal_places=4, default=0.0, help_text='Tipo de cambio MXN/USD vigente al momento del cierre del mes. Inmutable.', max_digits=12, verbose_name='Tipo de Cambio USD (Snapshot)')),
                ('tipo_cambio_eur_snapshot', models.DecimalField(decimal_places=4, default=0.0, help_text='Tipo de cambio MXN/EUR vigente al momento del cierre del mes. Inmutable.', max_digits=12, verbose_name='Tipo de Cambio EUR (Snapshot)')),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0.0, help_text='Suma de todos los ingresos del mes. Calculado al cerrar.', max_digits=18, verbose_name='Total Ingresos del Mes')),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0.0, help_text='Suma de todos los egresos del mes. Calculado al cerrar.', max_digits=18, verbose_name='Total Egresos del Mes')),
                ('resultado_neto', models.DecimalField(decimal_places=2, default=0.0, help_text='Diferencia total_ingresos - total_egresos del mes.', max_digits=18, verbose_name='Resultado Neto del Mes')),
                ('saldo_arrastre_inicio', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo en caja con el que inició el mes (arrastre del mes anterior).', max_digits=18, verbose_name='Saldo Arrastre Inicio de Mes')),
                ('saldo_arrastre_fin', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo final con el que cerró el mes. Se convierte en el inicio del siguiente.', max_digits=18, verbose_name='Saldo Arrastre Fin de Mes')),
                ('desglose_por_rubro', models.JSONField(blank=True, default=dict, help_text='Snapshot JSON con totales agrupados por rubro contable al momento del cierre. Ejemplo: {"VENTAS_BEBIDAS": 15000.00, "PAGO_RENTA": -8000.00}.', verbose_name='Desglose por Rubro Contable')),
                ('cerrado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que se cerró el período mensual.', null=True, verbose_name='Cerrado en')),
                ('observaciones', models.TextField(blank=True, help_text='Notas o comentarios del cierre mensual.', null=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('cerrado_por', models.ForeignKey(blank=True, help_text='Usuario que ejecutó el cierre del mes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('sucursal', models.ForeignKey(help_text='Sucursal a la que corresponde este estado de resultados mensual.', on_delete=django.db.models.deletion.PROTECT, related_name='libros_estado_resultados', to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Libro Estado de Resultados',
                'verbose_name_plural': 'Libros Estado de Resultados',
                'db_table': 'libro_estado_resultados',
                'ordering': ['-anio', '-mes', 'sucursal'],
                'unique_together': {('sucursal', 'anio', 'mes')},
            },
        ),
    ]
