# Generated by Django 6.0.2 on 2026-03-20 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuraciones_globales', '0004_configuracionglobal_estado_rubrocontable_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('nombre', models.CharField(help_text="Nombre único de la pestaña operativa (ej. 'ADMINISTRACION', 'BOOK', 'DOLARES').", max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('clave', models.CharField(help_text="Clave alfanumérica abreviada para identificar la categoría en el sistema (ej. 'ADMIN', 'BOOK').", max_length=50, unique=True, verbose_name='Clave Interna')),
                ('descripcion', models.TextField(blank=True, help_text='Explicación del tipo de movimientos que agrupa esta categoría operativa.', null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('MIXTO', 'Mixto')], default='MIXTO', help_text='Clasificación general del flujo de la pestaña: INGRESO, EGRESO o MIXTO (cuando puede tener ambos).', max_length=20, verbose_name='Tipo General')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Número de posición para ordenar las categorías en la interfaz. Menor número = aparece primero.', verbose_name='Orden de Visualización')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Categoría Operativa',
                'verbose_name_plural': 'Categorías Operativas',
                'db_table': 'categorias_operativas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('nombre', models.CharField(help_text="Nombre del movimiento específico (ej. 'VENTA DE CAFE', 'PAGO DE RENTA').", max_length=150, verbose_name='Nombre del Concepto')),
                ('clave', models.CharField(help_text="Código único del concepto en el sistema (ej. 'ADMIN_VENTA_CAFE').", max_length=60, unique=True, verbose_name='Clave del Concepto')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], help_text='Indica si este concepto representa una entrada (Ingreso) o salida (Egreso) de dinero.', max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del concepto y en qué contextos se aplica.', null=True, verbose_name='Descripción')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('categoria', models.ForeignKey(help_text='Pestaña a la que pertenece este concepto. Un concepto pertenece invariablemente a una única pestaña.', on_delete=django.db.models.deletion.PROTECT, related_name='conceptos', to='categoria_operativa.categoriaoperativa', verbose_name='Categoría Operativa')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('rubro_contable', models.ForeignKey(help_text='Rubro contable global al que se conecta este concepto para la consolidación del Estado de Resultados.', on_delete=django.db.models.deletion.PROTECT, related_name='conceptos', to='configuraciones_globales.rubrocontable', verbose_name='Rubro Contable')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'db_table': 'conceptos',
                'ordering': ['categoria', 'nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='DetalleParametrizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('nombre', models.CharField(help_text="Nombre descriptivo del campo adicional que se requiere para esta categoría (ej. 'responsable', 'area_origen').", max_length=100, verbose_name='Nombre del Campo')),
                ('clave', models.CharField(help_text="Identificador técnico del campo en formato snake_case (ej. 'responsable', 'monto_exacto').", max_length=80, verbose_name='Clave del Campo')),
                ('tipo_valor', models.CharField(choices=[('TEXT', 'Texto'), ('DECIMAL', 'Decimal'), ('INT', 'Entero'), ('BOOLEAN', 'Booleano'), ('DATE', 'Fecha'), ('DATETIME', 'Fecha y Hora')], default='TEXT', help_text='Tipo de dato esperado para este campo: TEXT, DECIMAL, INT, BOOLEAN, DATE o DATETIME.', max_length=20, verbose_name='Tipo de Valor')),
                ('requerido', models.BooleanField(default=False, help_text='Indica si este campo es obligatorio al registrar un movimiento en la categoría.', verbose_name='¿Es requerido?')),
                ('valor_defecto', models.CharField(blank=True, help_text='Valor predeterminado que se usa cuando no se proporciona uno explícitamente.', max_length=255, null=True, verbose_name='Valor por Defecto')),
                ('descripcion', models.TextField(blank=True, help_text='Explicación de para qué sirve este campo adicional y qué tipo de información captura.', null=True, verbose_name='Descripción')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('categoria', models.ForeignKey(help_text='Pestaña a la que pertenece este detalle parametrizado.', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_parametrizados', to='categoria_operativa.categoriaoperativa', verbose_name='Categoría Operativa')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Detalle Parametrizado',
                'verbose_name_plural': 'Detalles Parametrizados',
                'db_table': 'detalles_parametrizados',
                'ordering': ['categoria', 'nombre'],
                'unique_together': {('categoria', 'clave')},
            },
        ),
    ]
