# Generated by Django 6.0.2 on 2026-03-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_operativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto',
            name='es_recurrente',
            field=models.BooleanField(default=False, help_text='Indica si este concepto es recurrente (se repite periódicamente o diariamente).', verbose_name='¿Es Recurrente?'),
        ),
    ]
