# Generated by Django 6.0.3 on 2026-03-21 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_operativa', '0002_concepto_es_recurrente'),
        ('configuraciones_globales', '0005_cargar_rubros_gastos_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='rubro_contable',
            field=models.ForeignKey(blank=True, help_text='Rubro contable global opcional para consolidación del Estado de Resultados. Puede omitirse en conceptos no contables.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos', to='configuraciones_globales.rubrocontable', verbose_name='Rubro Contable'),
        ),
    ]
