# Generated by Django 6.0.3 on 2026-03-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_operativa', '0003_alter_concepto_rubro_contable'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto',
            name='requiere_imagen',
            field=models.BooleanField(default=False, help_text='Indica si este concepto solicita evidencia opcional en imagen o archivo (ej. recibo de pago o comprobante bancario).', verbose_name='¿Requiere Imagen?'),
        ),
    ]
