# Generated by Django 6.0.3 on 2026-04-16 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def marcar_categorias_con_saldo_inicial(apps, schema_editor):
    CategoriaOperativa = apps.get_model('categoria_operativa', 'CategoriaOperativa')

    patrones_habilitados = (
        'ADMINISTRACION',
        'DOLARES',
        'BANCO',
        'BANCOS',
        'BANORTE',
        'BANCOMER',
        'BBVB',
    )

    categorias = list(CategoriaOperativa.objects.all())
    categorias_actualizar = []

    for categoria in categorias:
        huella = f"{categoria.nombre or ''} {categoria.clave or ''}".upper()
        if any(patron in huella for patron in patrones_habilitados):
            categoria.usa_saldo_inicial = True
            categorias_actualizar.append(categoria)

    if categorias_actualizar:
        CategoriaOperativa.objects.bulk_update(categorias_actualizar, ['usa_saldo_inicial'])


def desmarcar_categorias_con_saldo_inicial(apps, schema_editor):
    CategoriaOperativa = apps.get_model('categoria_operativa', 'CategoriaOperativa')
    CategoriaOperativa.objects.update(usa_saldo_inicial=False)


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0004_sucursal_fondos_fijos'),
        ('categoria_operativa', '0004_concepto_requiere_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaoperativa',
            name='usa_saldo_inicial',
            field=models.BooleanField(default=False, help_text='Indica si la categoría requiere manejo de saldo inicial mensual con arrastre automático entre meses.', verbose_name='¿Usa saldo inicial mensual?'),
        ),
        migrations.CreateModel(
            name='SaldoInicialCategoriaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('anio', models.PositiveSmallIntegerField(help_text='Año contable del saldo inicial mensual (ej. 2026).', verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(help_text='Mes contable del saldo inicial (1=Enero ... 12=Diciembre).', verbose_name='Mes')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo de arrastre con el que inicia la categoría en el mes contable para la sucursal.', max_digits=18, verbose_name='Saldo Inicial del Mes')),
                ('origen_saldo_inicial', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], default='MANUAL', help_text='Define si el saldo inicial fue capturado manualmente o generado de forma automática.', max_length=20, verbose_name='Origen del Saldo Inicial')),
                ('bloqueado_edicion', models.BooleanField(default=True, help_text='Cuando está activo, el saldo inicial del mes no puede modificarse de forma manual.', verbose_name='¿Bloqueado para edición?')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('categoria', models.ForeignKey(help_text='Categoría operativa que usa este saldo inicial de arrastre mensual.', on_delete=django.db.models.deletion.PROTECT, related_name='saldos_iniciales_mensuales', to='categoria_operativa.categoriaoperativa', verbose_name='Categoría Operativa')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('sucursal', models.ForeignKey(help_text='Sucursal a la que corresponde este saldo inicial mensual por categoría.', on_delete=django.db.models.deletion.PROTECT, related_name='saldos_iniciales_categoria_mensual', to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Saldo Inicial de Categoría Mensual',
                'verbose_name_plural': 'Saldos Iniciales de Categoría Mensual',
                'db_table': 'saldos_iniciales_categoria_mensual',
                'ordering': ['-anio', '-mes', 'sucursal', 'categoria'],
                'unique_together': {('sucursal', 'categoria', 'anio', 'mes')},
            },
        ),
        migrations.RunPython(marcar_categorias_con_saldo_inicial, desmarcar_categorias_con_saldo_inicial),
    ]
