# Generated by Django 6.0.2 on 2026-04-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_operativa', '0005_categoriaoperativa_usa_saldo_inicial_and_saldoinicialcategoriamensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto',
            name='medio_liquidez',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo en Sala'), ('BANCARIO', 'Bancario / Transferencia'), ('VIRTUAL', 'Pasarela Virtual (Billpocket, etc.)'), ('NO_APLICA', 'No Aplica / Informativo')], default='VIRTUAL', help_text='Clasifica si el movimiento representa dinero físico en sala (EFECTIVO), un depósito o transferencia bancaria (BANCARIO), una pasarela de pago virtual como Billpocket (VIRTUAL), o un concepto sin impacto en liquidez (NO_APLICA).', max_length=20, verbose_name='Medio de Liquidez'),
        ),
    ]
