# Generated by Django 6.0.2 on 2026-03-20 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Identificador único para el inicio de sesión.', max_length=80, unique=True, verbose_name='Nombre de Usuario')),
                ('nombre', models.CharField(help_text='Nombre completo del usuario.', max_length=150, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico del usuario (opcional).', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario puede iniciar sesión.', verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario tiene acceso al sitio de administración de Django.', verbose_name='Es Staff')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el usuario.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del usuario.', verbose_name='Actualizado en')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Sucursal a la que pertenece el usuario. Puede ser nulo si el usuario es global (aplica a toda la empresa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='sucursales.sucursal', verbose_name='Sucursal')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('codigo', models.CharField(help_text="Identificador único del permiso en formato MODULO_ACCION (ej. 'SUCURSALES_CREAR').", max_length=100, unique=True, verbose_name='Código del Permiso')),
                ('nombre', models.CharField(help_text="Nombre descriptivo y legible del permiso (ej. 'Crear Sucursales').", max_length=150, verbose_name='Nombre del Permiso')),
                ('modulo', models.CharField(help_text="Módulo o sección del sistema al que pertenece el permiso (ej. 'SUCURSALES', 'TESORERÍA').", max_length=80, verbose_name='Módulo')),
                ('descripcion', models.TextField(blank=True, help_text='Detalle sobre qué permite hacer este permiso dentro del sistema.', null=True, verbose_name='Descripción')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('nombre', models.CharField(help_text="Nombre único del rol dentro del sistema (ej. 'Administrador', 'Cajero').", max_length=80, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del alcance y responsabilidades que corresponden a este rol.', null=True, verbose_name='Descripción')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('permiso', models.ForeignKey(help_text='Permiso que se le otorga al rol.', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='usuarios.permiso', verbose_name='Permiso')),
                ('rol', models.ForeignKey(help_text='Rol al que se le asigna el permiso.', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='usuarios.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol – Permiso',
                'verbose_name_plural': 'Roles – Permisos',
                'db_table': 'roles_permisos',
                'unique_together': {('rol', 'permiso')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se asignó el rol al usuario.', verbose_name='Asignado en')),
                ('rol', models.ForeignKey(help_text='Rol que se le asigna al usuario.', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to='usuarios.rol', verbose_name='Rol')),
                ('usuario', models.ForeignKey(help_text='Usuario al que se le asigna el rol.', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario – Rol',
                'verbose_name_plural': 'Usuarios – Roles',
                'db_table': 'usuarios_roles',
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
