# Generated by Django 6.0.3 on 2026-04-16 17:48

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario. Se guarda en media/<casino>/<id_usuario>/images/.', null=True, upload_to=usuarios.models.construir_ruta_imagen_perfil_usuario, verbose_name='Foto de Perfil'),
        ),
    ]
