# Generated by Django 6.0.3 on 2026-04-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='requiere_cambio_password',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña de forma obligatoria al iniciar sesión.', verbose_name='Requiere cambio de contraseña'),
        ),
    ]
