# Generated by Django 6.0.3 on 2026-04-20 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_requiere_cambio_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSoporteTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('folio', models.CharField(db_index=True, help_text='Folio único del ticket de soporte (ej. ST-20260419-120300-15-AB12CD).', max_length=60, unique=True, verbose_name='Folio')),
                ('usuario_nombre', models.CharField(help_text='Nombre visible del usuario al momento de levantar el ticket.', max_length=180, verbose_name='Nombre del usuario')),
                ('usuario_username', models.CharField(help_text='Identificador de cuenta del usuario al momento de levantar el ticket.', max_length=100, verbose_name='Username del usuario')),
                ('usuario_correo', models.EmailField(blank=True, help_text='Correo del usuario al momento de levantar el ticket.', max_length=254, null=True, verbose_name='Correo del usuario')),
                ('usuario_sucursal', models.CharField(blank=True, default='', help_text='Sucursal asociada al usuario al momento de levantar el ticket.', max_length=180, verbose_name='Sucursal del usuario')),
                ('usuario_roles', models.JSONField(blank=True, default=list, help_text='Lista de roles del usuario al momento de levantar el ticket.', verbose_name='Roles del usuario')),
                ('problema_principal', models.CharField(help_text='Clave del problema principal seleccionado en formulario.', max_length=40, verbose_name='Problema principal (código)')),
                ('problema_principal_etiqueta', models.CharField(help_text='Etiqueta textual del problema principal.', max_length=220, verbose_name='Problema principal')),
                ('areas_afectadas', models.JSONField(blank=True, default=list, help_text='Lista de claves de áreas afectadas seleccionadas.', verbose_name='Áreas afectadas (códigos)')),
                ('areas_afectadas_etiquetas', models.JSONField(blank=True, default=list, help_text='Lista de etiquetas de áreas afectadas seleccionadas.', verbose_name='Áreas afectadas')),
                ('comportamiento_observado', models.CharField(help_text='Clave de comportamiento observado seleccionada.', max_length=50, verbose_name='Comportamiento observado (código)')),
                ('comportamiento_observado_etiqueta', models.CharField(help_text='Etiqueta textual del comportamiento observado.', max_length=220, verbose_name='Comportamiento observado')),
                ('prioridad', models.CharField(default='MEDIA', help_text='Clave de prioridad seleccionada.', max_length=20, verbose_name='Prioridad (código)')),
                ('prioridad_etiqueta', models.CharField(default='Media', help_text='Etiqueta textual de prioridad.', max_length=60, verbose_name='Prioridad')),
                ('dispositivo', models.CharField(default='ESCRITORIO', help_text='Clave del dispositivo reportado.', max_length=20, verbose_name='Dispositivo (código)')),
                ('dispositivo_etiqueta', models.CharField(default='Equipo de escritorio', help_text='Etiqueta textual de dispositivo.', max_length=80, verbose_name='Dispositivo')),
                ('pagina_afectada', models.CharField(blank=True, default='', help_text='Ruta/pantalla reportada por el usuario.', max_length=300, verbose_name='Página afectada')),
                ('descripcion_detallada', models.TextField(help_text='Descripción principal del incidente.', verbose_name='Descripción detallada')),
                ('pasos_reproduccion', models.TextField(blank=True, default='', help_text='Secuencia opcional para reproducir el incidente.', verbose_name='Pasos para reproducir')),
                ('bloqueo_operativo', models.BooleanField(default=False, help_text='Indica si el incidente bloquea operación diaria del usuario.', verbose_name='Bloqueo operativo')),
                ('estado_seguimiento', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('DESCARTADO', 'Descartado')], default='NUEVO', help_text='Estado de atención administrativa del ticket.', max_length=20, verbose_name='Estado de seguimiento')),
                ('notas_seguimiento', models.TextField(blank=True, default='', help_text='Notas internas del administrador sobre el avance/cierre.', verbose_name='Notas de seguimiento')),
                ('atendido_en', models.DateTimeField(blank=True, help_text='Fecha y hora de la última actualización de seguimiento.', null=True, verbose_name='Atendido en')),
                ('resuelto_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el ticket fue marcado como completado.', null=True, verbose_name='Resuelto en')),
                ('correo_soporte_enviado', models.BooleanField(default=False, help_text='Indica si el correo al canal de soporte técnico se envió correctamente.', verbose_name='Correo a soporte enviado')),
                ('correo_confirmacion_enviado', models.BooleanField(default=False, help_text='Indica si se notificó al usuario solicitante con folio del ticket.', verbose_name='Correo de confirmación enviado')),
                ('detalle_error_envio', models.TextField(blank=True, default='', help_text='Detalle técnico de errores de envío de correo (si aplica).', verbose_name='Detalle de error de envío')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('atendido_por', models.ForeignKey(blank=True, help_text='Administrador que actualizó el estado del ticket por última vez.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_soporte_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario autenticado que levantó el ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_soporte_levantados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
            options={
                'verbose_name': 'Ticket de Soporte Técnico',
                'verbose_name_plural': 'Tickets de Soporte Técnico',
                'db_table': 'tickets_soporte_tecnico',
                'ordering': ['-creado_en'],
            },
        ),
    ]
