# Generated by Django 6.0.3 on 2026-03-20 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, null=True, verbose_name='Valor actual')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Clave de Configuración')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor de Configuración')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
                'db_table': 'configuraciones_globales',
            },
        ),
        migrations.CreateModel(
            name='RubroContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, null=True, verbose_name='Valor actual')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Rubro')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20, verbose_name='Tipo de Rubro')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Rubro Contable',
                'verbose_name_plural': 'Rubros Contables',
                'db_table': 'rubro_contable',
            },
        ),
    ]
