# Generated by Django 6.0.2 on 2026-03-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones_globales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='tipo_valor',
            field=models.CharField(choices=[('STRING', 'Texto'), ('INT', 'Entero'), ('FLOAT', 'Decimal'), ('BOOLEAN', 'Booleano'), ('DATE', 'Fecha'), ('TIME', 'Hora'), ('DATETIME', 'Fecha y Hora'), ('JSON', 'JSON')], default='STRING', max_length=20, verbose_name='Tipo de Valor'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='valor',
            field=models.TextField(verbose_name='Valor de Configuración'),
        ),
    ]
