# Generated by Django 6.0.2 on 2026-03-20 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones_globales', '0002_configuracionglobal_tipo_valor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrocontable',
            name='padre',
            field=models.CharField(choices=[('NINGUNO', 'Ninguno'), ('INGRESOS', 'Ingresos'), ('GASTOS', 'Gastos'), ('CARGAR_FISCALES', 'Cargar Fiscales'), ('COCINA', 'Cosina'), ('JUEGO_VIVO', 'Juego Vivo'), ('PAGO_MAQUINAS', 'Pago Maquinas'), ('OTROS_INGRESOS', 'Otros Ingresos'), ('OTROS_GASTOS', 'Otros Gastos')], default='NINGUNO', help_text='Categoría o pestaña general a la que pertenece este rubro para su agrupación.', max_length=150, verbose_name='Padre del Rubro'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='clave',
            field=models.CharField(help_text='Identificador único para la variable de configuración (ej. TIPO_CAMBIO_DOLAR).', max_length=100, unique=True, verbose_name='Clave de Configuración'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Explicación detallada del propósito u observaciones de esta configuración.', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete).', null=True, verbose_name='Eliminado en'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='tipo_valor',
            field=models.CharField(choices=[('STRING', 'Texto'), ('INT', 'Entero'), ('FLOAT', 'Decimal'), ('BOOLEAN', 'Booleano'), ('DATE', 'Fecha'), ('TIME', 'Hora'), ('DATETIME', 'Fecha y Hora'), ('JSON', 'JSON')], default='STRING', help_text='Determina cómo debe ser interpretado o parseado el contenido del campo valor.', max_length=20, verbose_name='Tipo de Valor'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='valor',
            field=models.TextField(help_text='Valor asignado a la configuración. Se debe tratar según el tipo de valor.', verbose_name='Valor de Configuración'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='valor_actual',
            field=models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='valor_anterior',
            field=models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalles adicionales sobre lo que contempla este rubro.', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete).', null=True, verbose_name='Eliminado en'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='nombre',
            field=models.CharField(help_text='Nombre representativo y único del rubro contable.', max_length=150, unique=True, verbose_name='Nombre del Rubro'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], help_text='Clasificación general del rubro indicando si representa entrada (Ingreso) o salida (Egreso) de dinero.', max_length=20, verbose_name='Tipo de Rubro'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='valor_actual',
            field=models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='valor_anterior',
            field=models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior'),
        ),
    ]
