# Generated by Django 6.0.2 on 2026-03-20 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones_globales', '0003_rubrocontable_padre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='rubrocontable',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en'),
        ),
        migrations.AlterField(
            model_name='rubrocontable',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
    ]
