# Generated by Django 6.0.3 on 2026-04-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones_globales', '0007_alter_padrerubrocontable_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrerubrocontable',
            name='considerar_en_estado_resultados',
            field=models.BooleanField(default=True, help_text='Indica si los rubros de este padre deben impactar los totales generales del estado de resultados.', verbose_name='Considerar en Estado de Resultados'),
        ),
    ]
