# Generated by Django 6.0.3 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones_globales", "0008_padrerubrocontable_considerar_en_estado_resultados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubrocontable",
            name="nombre",
            field=models.CharField(
                help_text="Nombre representativo del rubro contable. Debe ser unico dentro de su padre de rubro.",
                max_length=150,
                verbose_name="Nombre del Rubro",
            ),
        ),
        migrations.AddConstraint(
            model_name="rubrocontable",
            constraint=models.UniqueConstraint(
                fields=("nombre", "padre"),
                name="uq_rubrocontable_nombre_padre",
            ),
        ),
    ]
