# Generated by Django 6.0.3 on 2026-04-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones_globales', '0009_rubrocontable_unique_nombre_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='visible_para_director',
            field=models.BooleanField(
                default=True,
                help_text='Indica si esta variable global puede ser consultada y editada por usuarios con rol DIRECTOR desde su cabina.',
                verbose_name='¿Visible para Director?'
            ),
        ),
    ]
