# Generated by Django 6.0.2 on 2026-03-20 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria_operativa', '0002_concepto_es_recurrente'),
        ('sucursales', '0003_alter_sucursal_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('fecha_contable', models.DateField(help_text='Fecha contable del reporte (siempre D-1: el día anterior al día operativo actual). Única por sucursal.', verbose_name='Fecha Contable')),
                ('estado_reporte', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', help_text='ABIERTO: permite modificaciones dentro del horario. CERRADO: registro bloqueado permanentemente.', max_length=10, verbose_name='Estado del Reporte')),
                ('saldo_arrastre_inicio', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo en caja al iniciar el día contable. Proviene del saldo_arrastre_fin del reporte anterior de esta sucursal.', max_digits=18, verbose_name='Saldo Arrastre Inicio')),
                ('saldo_arrastre_fin', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo en caja al cierre del día contable. Se convierte en el saldo_arrastre_inicio del siguiente reporte.', max_digits=18, verbose_name='Saldo Arrastre Fin')),
                ('tipo_cambio_usd_snapshot', models.DecimalField(decimal_places=4, default=0.0, help_text='Tipo de cambio MXN/USD vigente al momento de crear o cerrar el reporte. Se guarda como snapshot para garantizar integridad histórica.', max_digits=12, verbose_name='Tipo de Cambio USD (Snapshot)')),
                ('tipo_cambio_eur_snapshot', models.DecimalField(decimal_places=4, default=0.0, help_text='Tipo de cambio MXN/EUR vigente al momento de crear o cerrar el reporte. Se guarda como snapshot.', max_digits=12, verbose_name='Tipo de Cambio EUR (Snapshot)')),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0.0, help_text='Suma total de todos los movimientos de tipo INGRESO del día. Se recalcula automáticamente al cerrar.', max_digits=18, verbose_name='Total Ingresos del Día')),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0.0, help_text='Suma total de todos los movimientos de tipo EGRESO del día. Se recalcula automáticamente al cerrar.', max_digits=18, verbose_name='Total Egresos del Día')),
                ('resultado_neto', models.DecimalField(decimal_places=2, default=0.0, help_text='Diferencia entre total_ingresos y total_egresos. Representa el flujo neto del día contable.', max_digits=18, verbose_name='Resultado Neto del Día')),
                ('cerrado_en', models.DateTimeField(blank=True, help_text='Fecha y hora exacta en que se realizó el cierre del día contable.', null=True, verbose_name='Cerrado en')),
                ('observaciones', models.TextField(blank=True, help_text='Notas o comentarios adicionales sobre el cierre del día.', null=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('cerrado_por', models.ForeignKey(blank=True, help_text='Usuario que ejecutó el cierre del día.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('sucursal', models.ForeignKey(help_text='Sucursal a la que pertenece este reporte diario.', on_delete=django.db.models.deletion.PROTECT, related_name='reportes_diarios', to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Reporte Diario',
                'verbose_name_plural': 'Reportes Diarios',
                'db_table': 'reportes_diarios',
                'ordering': ['-fecha_contable', 'sucursal'],
                'unique_together': {('sucursal', 'fecha_contable')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del movimiento en la moneda base (MXN). Siempre positivo; el tipo (ingreso/egreso) viene del concepto.', max_digits=18, verbose_name='Monto')),
                ('monto_divisa', models.DecimalField(blank=True, decimal_places=2, help_text='Monto en divisa extranjera si aplica (ej. USD o EUR). Nulo si el movimiento es solo en MXN.', max_digits=18, null=True, verbose_name='Monto en Divisa')),
                ('tipo_divisa', models.CharField(blank=True, help_text="Código de la divisa del campo monto_divisa (ej. 'USD', 'EUR'). Nulo si solo aplica MXN.", max_length=10, null=True, verbose_name='Tipo de Divisa')),
                ('detalles_snapshot', models.JSONField(blank=True, default=dict, help_text='Valores de los detalles parametrizados de la categoría al momento del registro, guardados como JSON inmutable. Ejemplo: {"responsable": "Juan", "area_origen": "Caja"}.', verbose_name='Detalles Parametrizados (Snapshot)')),
                ('notas', models.TextField(blank=True, help_text='Observaciones o aclaraciones específicas de este movimiento.', null=True, verbose_name='Notas')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('concepto', models.ForeignKey(help_text="Concepto operativo que clasifica este movimiento (ej. 'VENTA DE CAFE').", on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_diarios', to='categoria_operativa.concepto', verbose_name='Concepto')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('reporte', models.ForeignKey(help_text='Reporte diario al que pertenece este movimiento.', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='reportes_diarios.reportediario', verbose_name='Reporte Diario')),
            ],
            options={
                'verbose_name': 'Movimiento Diario',
                'verbose_name_plural': 'Movimientos Diarios',
                'db_table': 'movimientos_diarios',
                'ordering': ['reporte', 'concepto__categoria__orden'],
            },
        ),
    ]
