# Generated by Django 6.0.3 on 2026-03-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_diarios', '0002_historicalmovimientodiario_historicalreportediario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimientodiario',
            name='archivo_respaldo',
            field=models.TextField(blank=True, help_text='Comprobante opcional del movimiento (imagen, PDF u otro archivo permitido).', max_length=100, null=True, verbose_name='Archivo de Respaldo'),
        ),
        migrations.AddField(
            model_name='movimientodiario',
            name='archivo_respaldo',
            field=models.FileField(blank=True, help_text='Comprobante opcional del movimiento (imagen, PDF u otro archivo permitido).', null=True, upload_to='comprobantes_movimientos/%Y/%m/%d/', verbose_name='Archivo de Respaldo'),
        ),
    ]
