# Generated by Django 6.0.3 on 2026-03-31 01:11

import reportes_diarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_diarios', '0003_historicalmovimientodiario_archivo_respaldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmovimientodiario',
            name='archivo_respaldo',
            field=models.TextField(blank=True, help_text='Comprobante opcional del movimiento (imagen, PDF u otro archivo permitido).', max_length=500, null=True, verbose_name='Archivo de Respaldo'),
        ),
        migrations.AlterField(
            model_name='movimientodiario',
            name='archivo_respaldo',
            field=models.FileField(blank=True, help_text='Comprobante opcional del movimiento (imagen, PDF u otro archivo permitido).', max_length=500, null=True, upload_to=reportes_diarios.models.construir_ruta_archivo_respaldo, verbose_name='Archivo de Respaldo'),
        ),
    ]
