# Generated by Django 6.0.2 on 2026-04-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_diarios', '0004_alter_historicalmovimientodiario_archivo_respaldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreportediario',
            name='correo_enviado',
            field=models.BooleanField(default=False, help_text='Indica si el correo de notificación de cierre ha sido enviado. Previene envíos duplicados.', verbose_name='Correo de Cierre Enviado'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='correo_enviado',
            field=models.BooleanField(default=False, help_text='Indica si el correo de notificación de cierre ha sido enviado. Previene envíos duplicados.', verbose_name='Correo de Cierre Enviado'),
        ),
    ]
