# Generated by Django 6.0.2 on 2026-03-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FondoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('monto_autorizado', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto máximo autorizado para el fondo fijo de la sucursal en MXN.', max_digits=18, verbose_name='Monto Autorizado')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo disponible actual en el fondo fijo. Se actualiza con cada movimiento registrado.', max_digits=18, verbose_name='Saldo Actual')),
                ('moneda', models.CharField(default='MXN', help_text='Código de la moneda en que opera el fondo fijo (ej. MXN, USD).', max_length=10, verbose_name='Moneda')),
                ('observaciones', models.TextField(blank=True, help_text='Notas o comentarios adicionales relevantes para la administración del fondo.', null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Fondo Fijo',
                'verbose_name_plural': 'Fondos Fijos',
                'db_table': 'fondos_fijos',
            },
        ),
    ]
