# Generated by Django 6.0.3 on 2026-03-21 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def poblar_nombre_fondo_fijo(apps, schema_editor):
    FondoFijo = apps.get_model('fondos_fijos', 'FondoFijo')
    for fondo in FondoFijo.objects.all().iterator():
        fondo.nombre = f"Fondo {fondo.id}"
        fondo.save(update_fields=['nombre'])


class Migration(migrations.Migration):

    dependencies = [
        ('fondos_fijos', '0002_initial'),
        ('sucursales', '0003_alter_sucursal_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fondofijo',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='fondofijo',
            name='monto_autorizado',
        ),
        migrations.RemoveField(
            model_name='fondofijo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='fondofijo',
            name='saldo_actual',
        ),
        migrations.RemoveField(
            model_name='fondofijo',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='fondofijo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del propósito operativo del fondo fijo dentro de la organización.', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='fondofijo',
            name='nombre',
            field=models.CharField(blank=True, help_text="Nombre único del tipo de fondo fijo (ej. 'Caja Chica', 'Juego Vivo').", max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.RunPython(poblar_nombre_fondo_fijo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fondofijo',
            name='nombre',
            field=models.CharField(help_text="Nombre único del tipo de fondo fijo (ej. 'Caja Chica', 'Juego Vivo').", max_length=120, unique=True, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='SucursalFondoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('monto_asignado', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor monetario asignado para este fondo fijo en la sucursal, con 2 decimales.', max_digits=18, verbose_name='Monto asignado')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('fondo_fijo', models.ForeignKey(help_text='Tipo de fondo fijo del catálogo maestro que se asigna a la sucursal.', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_sucursales', to='fondos_fijos.fondofijo', verbose_name='Fondo fijo')),
                ('sucursal', models.ForeignKey(help_text='Sucursal a la que se asigna el fondo fijo.', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_fondos_fijos', to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Sucursal Fondo Fijo',
                'verbose_name_plural': 'Sucursales Fondos Fijos',
                'db_table': 'sucursales_fondos_fijos',
                'unique_together': {('sucursal', 'fondo_fijo')},
            },
        ),
    ]
