# Generated by Django 6.0.2 on 2026-03-20 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en')),
                ('valor_anterior', models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior')),
                ('valor_actual', models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual')),
                ('nombre', models.CharField(help_text="Nombre comercial único que identifica a la sucursal (ej. 'Sala Morelia Centro').", max_length=150, unique=True, verbose_name='Nombre de la Sucursal')),
                ('clave', models.CharField(help_text="Código alfanumérico corto de identificación interna de la sucursal (ej. 'MOR-01').", max_length=30, unique=True, verbose_name='Clave Interna')),
                ('direccion', models.TextField(blank=True, help_text='Domicilio completo de la sucursal.', null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad o municipio donde se ubica la sucursal.', max_length=100, null=True, verbose_name='Ciudad')),
                ('estado_republica', models.CharField(blank=True, help_text='Entidad federativa donde se ubica la sucursal.', max_length=100, null=True, verbose_name='Estado (República)')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto de la sucursal.', max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico institucional de la sucursal.', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('encargado', models.CharField(blank=True, help_text='Nombre del responsable operativo de la sucursal.', max_length=150, null=True, verbose_name='Responsable / Encargado')),
                ('fondo_inicial', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto inicial asignado al fondo fijo de la sucursal en moneda nacional (MXN).', max_digits=18, verbose_name='Fondo Inicial')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
                'ordering': ['nombre'],
            },
        ),
    ]
