# Generated by Django 6.0.2 on 2026-03-20 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_sucursal_fk_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.', verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad o municipio donde se ubica la sucursal.', max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='clave',
            field=models.CharField(help_text="Código alfanumérico corto de identificación interna de la sucursal (ej. 'MOR-01').", max_length=30, unique=True, verbose_name='Clave Interna'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='correo',
            field=models.EmailField(blank=True, help_text='Correo electrónico institucional de la sucursal.', max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.TextField(blank=True, help_text='Domicilio completo de la sucursal.', null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue marcado como eliminado (Soft Delete). Si es nulo, el registro está vigente.', null=True, verbose_name='Eliminado en'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro (Soft Delete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_eliminado_por', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='encargado',
            field=models.CharField(blank=True, help_text='Nombre del responsable operativo de la sucursal.', max_length=150, null=True, verbose_name='Responsable / Encargado'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', help_text='Estado actual del registro dentro del ciclo de vida: ACTIVO, INACTIVO, BLOQUEADO o ELIMINADO.', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='estado_republica',
            field=models.CharField(blank=True, help_text='Entidad federativa donde se ubica la sucursal.', max_length=100, null=True, verbose_name='Estado (República)'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='fondo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto inicial asignado al fondo fijo de la sucursal en moneda nacional (MXN).', max_digits=18, verbose_name='Fondo Inicial'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(help_text="Nombre comercial único que identifica a la sucursal (ej. 'Sala Morelia Centro').", max_length=150, unique=True, verbose_name='Nombre de la Sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto de la sucursal.', max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='valor_actual',
            field=models.JSONField(blank=True, help_text='Estado del registro después de la última modificación (Auditoría).', null=True, verbose_name='Valor actual'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='valor_anterior',
            field=models.JSONField(blank=True, help_text='Estado del registro antes de la última modificación (Auditoría).', null=True, verbose_name='Valor anterior'),
        ),
    ]
