# Generated by Django 6.0.3 on 2026-03-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos_fijos', '0003_remove_fondofijo_moneda_and_more'),
        ('sucursales', '0003_alter_sucursal_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='fondos_fijos',
            field=models.ManyToManyField(help_text='Fondos fijos asignados a la sucursal mediante la tabla intermedia con monto por sucursal.', related_name='sucursales', through='fondos_fijos.SucursalFondoFijo', to='fondos_fijos.fondofijo', verbose_name='Fondos fijos'),
        ),
    ]
