# Generated by Django 6.0.3 on 2026-04-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0004_sucursal_fondos_fijos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='fondo_inicial',
        ),
    ]
